FROM alpine:3.22

ENV SAMPLE_VERSION=1.0.0
ENV SAMPLE_CHANNEL=stable SAMPLE_RUNTIME=integration
ENV EXTRA_SAMPLE_VERSION=0.1.0
ENV EXTRA_SAMPLE_VERSION=0.1.1
ENV DUPLICATE_SAMPLE_KEY=first
ENV DUPLICATE_SAMPLE_KEY=second
