name: Integration Update

on:
  schedule:
    - cron: "12 4 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    uses: snw35/cicd/.github/workflows/github.yaml@main
    with:
      WORKDIR: .
      IMAGE_TAG: SAMPLE_VERSION
      CICD_REF: ${{ vars.CICD_REF }}
    secrets: inherit

  create-release:
    needs: update
    if: github.ref_name == github.event.repository.default_branch && needs.update.outputs.changed == 'true'
    uses: snw35/cicd/.github/workflows/create-release.yaml@main
    with:
      targets_json: ${{ needs.update.outputs.targets }}
      CICD_REF: ${{ vars.CICD_REF }}
    secrets: inherit
